// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
	"time"
)

const consumeAccountToken = `-- name: ConsumeAccountToken :one
DELETE FROM account_tokens WHERE token_hash=$1 AND purpose=$2 AND expires_at>now() RETURNING user_id
`

type ConsumeAccountTokenParams struct {
	TokenHash string `json:"token_hash"`
	Purpose   string `json:"purpose"`
}

func (q *Queries) ConsumeAccountToken(ctx context.Context, arg ConsumeAccountTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, consumeAccountToken, arg.TokenHash, arg.Purpose)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const createAccountToken = `-- name: CreateAccountToken :exec
INSERT INTO account_tokens(token_hash,user_id,purpose,expires_at) VALUES($1,$2,$3,$4)
`

type CreateAccountTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAccountToken(ctx context.Context, arg CreateAccountTokenParams) error {
	_, err := q.db.Exec(ctx, createAccountToken,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)
`

type CreateSessionParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(email,handle,display_name,password_hash,email_verified) VALUES ($1,$2,$3,$4,$5) RETURNING id, email, handle, display_name, password_hash, email_verified, created_at
`

type CreateUserParams struct {
	Email         string `json:"email"`
	Handle        string `json:"handle"`
	DisplayName   string `json:"display_name"`
	PasswordHash  string `json:"password_hash"`
	EmailVerified bool   `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Handle,
		arg.DisplayName,
		arg.PasswordHash,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at<=now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const sessionUser = `-- name: SessionUser :one
SELECT u.id,u.handle,u.display_name,u.email,u.email_verified,s.expires_at
FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()
`

type SessionUserRow struct {
	ID            string    `json:"id"`
	Handle        string    `json:"handle"`
	DisplayName   string    `json:"display_name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) SessionUser(ctx context.Context, tokenHash string) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, tokenHash)
	var i SessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.ExpiresAt,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, handle, display_name, password_hash, email_verified, created_at FROM users WHERE email=$1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const userByHandle = `-- name: UserByHandle :one
SELECT id,handle,display_name FROM users WHERE handle=$1
`

type UserByHandleRow struct {
	ID          string `json:"id"`
	Handle      string `json:"handle"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UserByHandle(ctx context.Context, handle string) (UserByHandleRow, error) {
	row := q.db.QueryRow(ctx, userByHandle, handle)
	var i UserByHandleRow
	err := row.Scan(&i.ID, &i.Handle, &i.DisplayName)
	return i, err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users SET email_verified=true WHERE id=$1
`

func (q *Queries) VerifyUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
