// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
	"time"
)

const chatPage = `-- name: ChatPage :many
SELECT c.id,c.user_id,u.handle,u.display_name,c.body,c.created_at,c.client_id
FROM room_chat c JOIN users u ON u.id=c.user_id
WHERE c.room_id=$1 AND c.id>$2::bigint AND c.created_at>now()-interval '7 days'
AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE b.user_id=$3::uuid AND b.blocked_id=c.user_id)
ORDER BY c.id LIMIT 100
`

type ChatPageParams struct {
	RoomID   string `json:"room_id"`
	AfterID  int64  `json:"after_id"`
	ViewerID string `json:"viewer_id"`
}

type ChatPageRow struct {
	ID          int64     `json:"id"`
	UserID      string    `json:"user_id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	ClientID    string    `json:"client_id"`
}

func (q *Queries) ChatPage(ctx context.Context, arg ChatPageParams) ([]ChatPageRow, error) {
	rows, err := q.db.Query(ctx, chatPage, arg.RoomID, arg.AfterID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatPageRow{}
	for rows.Next() {
		var i ChatPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Handle,
			&i.DisplayName,
			&i.Body,
			&i.CreatedAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatRecentCount = `-- name: ChatRecentCount :one
SELECT count(*) FROM room_chat WHERE user_id=$1 AND created_at>now()-interval '10 seconds'
`

func (q *Queries) ChatRecentCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, chatRecentCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deliverOutbox = `-- name: DeliverOutbox :exec
UPDATE outbox SET delivered_at=now() WHERE id=$1
`

func (q *Queries) DeliverOutbox(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deliverOutbox, id)
	return err
}

const enqueue = `-- name: Enqueue :exec
INSERT INTO outbox(room_id,kind,payload) VALUES($1,$2,$3)
`

type EnqueueParams struct {
	RoomID  string `json:"room_id"`
	Kind    string `json:"kind"`
	Payload []byte `json:"payload"`
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.Exec(ctx, enqueue, arg.RoomID, arg.Kind, arg.Payload)
	return err
}

const existingChat = `-- name: ExistingChat :one
SELECT id, room_id, user_id, client_id, body, created_at FROM room_chat WHERE room_id=$1 AND user_id=$2 AND client_id=$3
`

type ExistingChatParams struct {
	RoomID   string `json:"room_id"`
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) ExistingChat(ctx context.Context, arg ExistingChatParams) (RoomChat, error) {
	row := q.db.QueryRow(ctx, existingChat, arg.RoomID, arg.UserID, arg.ClientID)
	var i RoomChat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.ClientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO room_chat(room_id,user_id,client_id,body) VALUES($1,$2,$3,$4) RETURNING id, room_id, user_id, client_id, body, created_at
`

type InsertChatParams struct {
	RoomID   string `json:"room_id"`
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
	Body     string `json:"body"`
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (RoomChat, error) {
	row := q.db.QueryRow(ctx, insertChat,
		arg.RoomID,
		arg.UserID,
		arg.ClientID,
		arg.Body,
	)
	var i RoomChat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.ClientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const pendingOutbox = `-- name: PendingOutbox :many
SELECT id, room_id, kind, payload, created_at, delivered_at FROM outbox WHERE delivered_at IS NULL ORDER BY id LIMIT 100
`

func (q *Queries) PendingOutbox(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, pendingOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeChat = `-- name: PurgeChat :exec
DELETE FROM room_chat WHERE created_at<=now()-interval '7 days'
`

func (q *Queries) PurgeChat(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeChat)
	return err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
DELETE FROM outbox WHERE delivered_at<now()-interval '1 day'
`

func (q *Queries) PurgeOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOutbox)
	return err
}
