// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
	"time"
)

const chatAuthor = `-- name: ChatAuthor :one
SELECT user_id FROM room_chat WHERE id=$1 AND room_id=$2 AND created_at>now()-interval '7 days'
`

type ChatAuthorParams struct {
	ID     int64  `json:"id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) ChatAuthor(ctx context.Context, arg ChatAuthorParams) (string, error) {
	row := q.db.QueryRow(ctx, chatAuthor, arg.ID, arg.RoomID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const chatPage = `-- name: ChatPage :many
SELECT c.id,c.user_id,u.handle,u.display_name,c.body,c.created_at,c.client_id
FROM room_chat c JOIN users u ON u.id=c.user_id
WHERE c.room_id=$1 AND c.id>$2::bigint AND c.created_at>now()-interval '7 days'
AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE b.user_id=$3::uuid AND b.blocked_id=c.user_id)
AND NOT EXISTS(SELECT 1 FROM user_mutes mu WHERE mu.user_id=$3::uuid AND mu.muted_id=c.user_id)
ORDER BY CASE WHEN $2::bigint=0 THEN -c.id ELSE c.id END LIMIT 100
`

type ChatPageParams struct {
	RoomID   string `json:"room_id"`
	AfterID  int64  `json:"after_id"`
	ViewerID string `json:"viewer_id"`
}

type ChatPageRow struct {
	ID          int64     `json:"id"`
	UserID      string    `json:"user_id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	ClientID    string    `json:"client_id"`
}

func (q *Queries) ChatPage(ctx context.Context, arg ChatPageParams) ([]ChatPageRow, error) {
	rows, err := q.db.Query(ctx, chatPage, arg.RoomID, arg.AfterID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatPageRow{}
	for rows.Next() {
		var i ChatPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Handle,
			&i.DisplayName,
			&i.Body,
			&i.CreatedAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatRecentCount = `-- name: ChatRecentCount :one
SELECT count(*) FROM room_chat WHERE user_id=$1 AND created_at>now()-interval '10 seconds'
`

func (q *Queries) ChatRecentCount(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, chatRecentCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMutes = `-- name: DeleteMutes :exec
DELETE FROM user_mutes WHERE user_id=$1 OR muted_id=$1
`

func (q *Queries) DeleteMutes(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteMutes, userID)
	return err
}

const enqueue = `-- name: Enqueue :exec
INSERT INTO outbox(room_id,kind,payload) VALUES($1,$2,$3)
`

type EnqueueParams struct {
	RoomID  string `json:"room_id"`
	Kind    string `json:"kind"`
	Payload []byte `json:"payload"`
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.Exec(ctx, enqueue, arg.RoomID, arg.Kind, arg.Payload)
	return err
}

const existingChat = `-- name: ExistingChat :one
SELECT id, room_id, user_id, client_id, body, created_at FROM room_chat WHERE room_id=$1 AND user_id=$2 AND client_id=$3
`

type ExistingChatParams struct {
	RoomID   string `json:"room_id"`
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) ExistingChat(ctx context.Context, arg ExistingChatParams) (RoomChat, error) {
	row := q.db.QueryRow(ctx, existingChat, arg.RoomID, arg.UserID, arg.ClientID)
	var i RoomChat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.ClientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO room_chat(room_id,user_id,client_id,body) VALUES($1,$2,$3,$4) RETURNING id, room_id, user_id, client_id, body, created_at
`

type InsertChatParams struct {
	RoomID   string `json:"room_id"`
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
	Body     string `json:"body"`
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (RoomChat, error) {
	row := q.db.QueryRow(ctx, insertChat,
		arg.RoomID,
		arg.UserID,
		arg.ClientID,
		arg.Body,
	)
	var i RoomChat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.ClientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMutes = `-- name: ListMutes :many
SELECT u.id,u.handle,u.display_name FROM user_mutes m JOIN users u ON u.id=m.muted_id
WHERE m.user_id=$1 AND u.deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 100
`

type ListMutesRow struct {
	ID          string `json:"id"`
	Handle      string `json:"handle"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListMutes(ctx context.Context, userID string) ([]ListMutesRow, error) {
	rows, err := q.db.Query(ctx, listMutes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMutesRow{}
	for rows.Next() {
		var i ListMutesRow
		if err := rows.Scan(&i.ID, &i.Handle, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const muteUser = `-- name: MuteUser :execrows
INSERT INTO user_mutes(user_id,muted_id)
SELECT $1::uuid,u.id FROM users u WHERE u.id=$2::uuid AND u.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type MuteUserParams struct {
	UserID  string `json:"user_id"`
	MutedID string `json:"muted_id"`
}

func (q *Queries) MuteUser(ctx context.Context, arg MuteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, muteUser, arg.UserID, arg.MutedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeChat = `-- name: PurgeChat :exec
DELETE FROM room_chat WHERE created_at<=now()-interval '7 days'
`

func (q *Queries) PurgeChat(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeChat)
	return err
}

const purgeOutbox = `-- name: PurgeOutbox :exec
DELETE FROM outbox WHERE created_at<now()-interval '1 day'
`

func (q *Queries) PurgeOutbox(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOutbox)
	return err
}

const reportChat = `-- name: ReportChat :execrows
INSERT INTO chat_reports(message_id,reporter_id,reason) VALUES($1,$2,$3) ON CONFLICT DO NOTHING
`

type ReportChatParams struct {
	MessageID  int64  `json:"message_id"`
	ReporterID string `json:"reporter_id"`
	Reason     string `json:"reason"`
}

func (q *Queries) ReportChat(ctx context.Context, arg ReportChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, reportChat, arg.MessageID, arg.ReporterID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unmuteUser = `-- name: UnmuteUser :exec
DELETE FROM user_mutes WHERE user_id=$1 AND muted_id=$2
`

type UnmuteUserParams struct {
	UserID  string `json:"user_id"`
	MutedID string `json:"muted_id"`
}

func (q *Queries) UnmuteUser(ctx context.Context, arg UnmuteUserParams) error {
	_, err := q.db.Exec(ctx, unmuteUser, arg.UserID, arg.MutedID)
	return err
}
