// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package store

import (
	"context"
)

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS(SELECT 1 FROM match_participants WHERE match_id=$1 AND user_id=$2)
`

type IsParticipantParams struct {
	MatchID string `json:"match_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.MatchID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const latestSnapshot = `-- name: LatestSnapshot :one
SELECT match_id, revision, schema_version, state, created_at FROM game_snapshots WHERE match_id=$1 ORDER BY revision DESC LIMIT 1
`

func (q *Queries) LatestSnapshot(ctx context.Context, matchID string) (GameSnapshot, error) {
	row := q.db.QueryRow(ctx, latestSnapshot, matchID)
	var i GameSnapshot
	err := row.Scan(
		&i.MatchID,
		&i.Revision,
		&i.SchemaVersion,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const match = `-- name: Match :one
SELECT id, room_id, game_id, rules_version, status, revision, winner_id, created_at, finished_at, version, end_reason, ended_by, awaiting_since FROM matches WHERE id=$1
`

func (q *Queries) Match(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, match, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RulesVersion,
		&i.Status,
		&i.Revision,
		&i.WinnerID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Version,
		&i.EndReason,
		&i.EndedBy,
		&i.AwaitingSince,
	)
	return i, err
}

const visibleEvents = `-- name: VisibleEvents :many
SELECT revision,event_index,kind,payload FROM game_events WHERE match_id=$1 AND revision>$2::bigint
AND (public OR audience_user_id=$3::uuid) ORDER BY revision,event_index LIMIT 100
`

type VisibleEventsParams struct {
	MatchID       string `json:"match_id"`
	AfterRevision int64  `json:"after_revision"`
	ViewerID      string `json:"viewer_id"`
}

type VisibleEventsRow struct {
	Revision   int64  `json:"revision"`
	EventIndex int32  `json:"event_index"`
	Kind       string `json:"kind"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) VisibleEvents(ctx context.Context, arg VisibleEventsParams) ([]VisibleEventsRow, error) {
	rows, err := q.db.Query(ctx, visibleEvents, arg.MatchID, arg.AfterRevision, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisibleEventsRow{}
	for rows.Next() {
		var i VisibleEventsRow
		if err := rows.Scan(
			&i.Revision,
			&i.EventIndex,
			&i.Kind,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
