// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeMatchesForUser = `-- name: ActiveMatchesForUser :many
SELECT m.id FROM matches m JOIN match_participants p ON p.match_id=m.id
WHERE p.user_id=$1 AND m.status IN ('playing','paused')
`

func (q *Queries) ActiveMatchesForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, activeMatchesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO match_participants(match_id,user_id,seat,disconnected_at) VALUES($1,$2,$3,now())
`

type AddParticipantParams struct {
	MatchID string `json:"match_id"`
	UserID  string `json:"user_id"`
	Seat    int32  `json:"seat"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.MatchID, arg.UserID, arg.Seat)
	return err
}

const advanceMatch = `-- name: AdvanceMatch :exec
UPDATE matches SET revision=$2,version=version+1,awaiting_since=now() WHERE id=$1
`

type AdvanceMatchParams struct {
	ID       string `json:"id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) AdvanceMatch(ctx context.Context, arg AdvanceMatchParams) error {
	_, err := q.db.Exec(ctx, advanceMatch, arg.ID, arg.Revision)
	return err
}

const bumpMatchVersion = `-- name: BumpMatchVersion :exec
UPDATE matches SET version=version+1 WHERE id=$1
`

func (q *Queries) BumpMatchVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpMatchVersion, id)
	return err
}

const clearAbandonVotes = `-- name: ClearAbandonVotes :exec
UPDATE match_participants SET abandon_vote=false WHERE match_id=$1
`

func (q *Queries) ClearAbandonVotes(ctx context.Context, matchID string) error {
	_, err := q.db.Exec(ctx, clearAbandonVotes, matchID)
	return err
}

const controllerDisconnected = `-- name: ControllerDisconnected :execrows
UPDATE match_participants SET disconnected_at=now()
WHERE match_id=$1 AND user_id=$2 AND controller_generation=$3 AND disconnected_at IS NULL
`

type ControllerDisconnectedParams struct {
	MatchID              string `json:"match_id"`
	UserID               string `json:"user_id"`
	ControllerGeneration int64  `json:"controller_generation"`
}

func (q *Queries) ControllerDisconnected(ctx context.Context, arg ControllerDisconnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, controllerDisconnected, arg.MatchID, arg.UserID, arg.ControllerGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const controllerHeartbeat = `-- name: ControllerHeartbeat :execrows
UPDATE match_participants SET last_seen_at=now()
WHERE match_id=$1 AND user_id=$2 AND controller_generation=$3 AND disconnected_at IS NULL
`

type ControllerHeartbeatParams struct {
	MatchID              string `json:"match_id"`
	UserID               string `json:"user_id"`
	ControllerGeneration int64  `json:"controller_generation"`
}

func (q *Queries) ControllerHeartbeat(ctx context.Context, arg ControllerHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, controllerHeartbeat, arg.MatchID, arg.UserID, arg.ControllerGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const controllerReturned = `-- name: ControllerReturned :execrows
UPDATE match_participants SET last_seen_at=now(),disconnected_at=NULL
WHERE match_id=$1 AND user_id=$2 AND controller_generation=$3 AND disconnected_at IS NOT NULL
`

type ControllerReturnedParams struct {
	MatchID              string `json:"match_id"`
	UserID               string `json:"user_id"`
	ControllerGeneration int64  `json:"controller_generation"`
}

func (q *Queries) ControllerReturned(ctx context.Context, arg ControllerReturnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, controllerReturned, arg.MatchID, arg.UserID, arg.ControllerGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches(room_id,game_id,rules_version,status) VALUES($1,$2,$3,'paused') RETURNING id, room_id, game_id, rules_version, status, revision, winner_id, created_at, finished_at, version, end_reason, ended_by, awaiting_since
`

type CreateMatchParams struct {
	RoomID       string `json:"room_id"`
	GameID       string `json:"game_id"`
	RulesVersion string `json:"rules_version"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch, arg.RoomID, arg.GameID, arg.RulesVersion)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RulesVersion,
		&i.Status,
		&i.Revision,
		&i.WinnerID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Version,
		&i.EndReason,
		&i.EndedBy,
		&i.AwaitingSince,
	)
	return i, err
}

const endMatch = `-- name: EndMatch :exec
UPDATE matches SET status=$1,winner_id=$2,end_reason=$3,ended_by=$4,finished_at=now(),version=version+1
WHERE id=$5
`

type EndMatchParams struct {
	Status    string      `json:"status"`
	WinnerID  *string     `json:"winner_id"`
	EndReason pgtype.Text `json:"end_reason"`
	EndedBy   *string     `json:"ended_by"`
	ID        string      `json:"id"`
}

func (q *Queries) EndMatch(ctx context.Context, arg EndMatchParams) error {
	_, err := q.db.Exec(ctx, endMatch,
		arg.Status,
		arg.WinnerID,
		arg.EndReason,
		arg.EndedBy,
		arg.ID,
	)
	return err
}

const expiredMatches = `-- name: ExpiredMatches :many
SELECT m.id FROM matches m WHERE m.status IN ('playing','paused')
AND NOT EXISTS(SELECT 1 FROM match_participants p WHERE p.match_id=m.id AND (p.disconnected_at IS NULL OR p.disconnected_at > now()-interval '24 hours'))
`

func (q *Queries) ExpiredMatches(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, expiredMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCommand = `-- name: FindCommand :one
SELECT match_id, actor_id, command_id, request_hash, resulting_revision, result FROM game_commands WHERE match_id=$1 AND actor_id=$2 AND command_id=$3
`

type FindCommandParams struct {
	MatchID   string `json:"match_id"`
	ActorID   string `json:"actor_id"`
	CommandID string `json:"command_id"`
}

func (q *Queries) FindCommand(ctx context.Context, arg FindCommandParams) (GameCommand, error) {
	row := q.db.QueryRow(ctx, findCommand, arg.MatchID, arg.ActorID, arg.CommandID)
	var i GameCommand
	err := row.Scan(
		&i.MatchID,
		&i.ActorID,
		&i.CommandID,
		&i.RequestHash,
		&i.ResultingRevision,
		&i.Result,
	)
	return i, err
}

const idleMatches = `-- name: IdleMatches :many
SELECT id FROM matches WHERE status='playing' AND awaiting_since < now()-make_interval(secs => $1::float8)
ORDER BY awaiting_since LIMIT 50
`

func (q *Queries) IdleMatches(ctx context.Context, timeoutSeconds float64) ([]string, error) {
	rows, err := q.db.Query(ctx, idleMatches, timeoutSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommand = `-- name: InsertCommand :exec
INSERT INTO game_commands(match_id,actor_id,command_id,request_hash,resulting_revision,result) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertCommandParams struct {
	MatchID           string `json:"match_id"`
	ActorID           string `json:"actor_id"`
	CommandID         string `json:"command_id"`
	RequestHash       string `json:"request_hash"`
	ResultingRevision int64  `json:"resulting_revision"`
	Result            []byte `json:"result"`
}

func (q *Queries) InsertCommand(ctx context.Context, arg InsertCommandParams) error {
	_, err := q.db.Exec(ctx, insertCommand,
		arg.MatchID,
		arg.ActorID,
		arg.CommandID,
		arg.RequestHash,
		arg.ResultingRevision,
		arg.Result,
	)
	return err
}

const insertGameEvent = `-- name: InsertGameEvent :exec
INSERT INTO game_events(match_id,revision,event_index,kind,audience_user_id,public,payload) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type InsertGameEventParams struct {
	MatchID        string  `json:"match_id"`
	Revision       int64   `json:"revision"`
	EventIndex     int32   `json:"event_index"`
	Kind           string  `json:"kind"`
	AudienceUserID *string `json:"audience_user_id"`
	Public         bool    `json:"public"`
	Payload        []byte  `json:"payload"`
}

func (q *Queries) InsertGameEvent(ctx context.Context, arg InsertGameEventParams) error {
	_, err := q.db.Exec(ctx, insertGameEvent,
		arg.MatchID,
		arg.Revision,
		arg.EventIndex,
		arg.Kind,
		arg.AudienceUserID,
		arg.Public,
		arg.Payload,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO game_snapshots(match_id,revision,schema_version,state) VALUES($1,$2,$3,$4)
`

type InsertSnapshotParams struct {
	MatchID       string `json:"match_id"`
	Revision      int64  `json:"revision"`
	SchemaVersion int32  `json:"schema_version"`
	State         []byte `json:"state"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.MatchID,
		arg.Revision,
		arg.SchemaVersion,
		arg.State,
	)
	return err
}

const latestRoomMatch = `-- name: LatestRoomMatch :one
SELECT id, room_id, game_id, rules_version, status, revision, winner_id, created_at, finished_at, version, end_reason, ended_by, awaiting_since FROM matches WHERE room_id=$1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestRoomMatch(ctx context.Context, roomID string) (Match, error) {
	row := q.db.QueryRow(ctx, latestRoomMatch, roomID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RulesVersion,
		&i.Status,
		&i.Revision,
		&i.WinnerID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Version,
		&i.EndReason,
		&i.EndedBy,
		&i.AwaitingSince,
	)
	return i, err
}

const lockMatch = `-- name: LockMatch :one
SELECT id, room_id, game_id, rules_version, status, revision, winner_id, created_at, finished_at, version, end_reason, ended_by, awaiting_since FROM matches WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockMatch(ctx context.Context, id string) (Match, error) {
	row := q.db.QueryRow(ctx, lockMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RulesVersion,
		&i.Status,
		&i.Revision,
		&i.WinnerID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.Version,
		&i.EndReason,
		&i.EndedBy,
		&i.AwaitingSince,
	)
	return i, err
}

const matchParticipant = `-- name: MatchParticipant :one
SELECT match_id, user_id, seat, controller_generation, disconnected_at, last_seen_at, abandon_vote FROM match_participants WHERE match_id=$1 AND user_id=$2
`

type MatchParticipantParams struct {
	MatchID string `json:"match_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) MatchParticipant(ctx context.Context, arg MatchParticipantParams) (MatchParticipant, error) {
	row := q.db.QueryRow(ctx, matchParticipant, arg.MatchID, arg.UserID)
	var i MatchParticipant
	err := row.Scan(
		&i.MatchID,
		&i.UserID,
		&i.Seat,
		&i.ControllerGeneration,
		&i.DisconnectedAt,
		&i.LastSeenAt,
		&i.AbandonVote,
	)
	return i, err
}

const matchParticipants = `-- name: MatchParticipants :many
SELECT p.user_id,p.seat,p.controller_generation,p.disconnected_at,p.last_seen_at,p.abandon_vote,u.handle,u.display_name
FROM match_participants p JOIN users u ON u.id=p.user_id WHERE p.match_id=$1 ORDER BY p.seat
`

type MatchParticipantsRow struct {
	UserID               string     `json:"user_id"`
	Seat                 int32      `json:"seat"`
	ControllerGeneration int64      `json:"controller_generation"`
	DisconnectedAt       *time.Time `json:"disconnected_at"`
	LastSeenAt           time.Time  `json:"last_seen_at"`
	AbandonVote          bool       `json:"abandon_vote"`
	Handle               string     `json:"handle"`
	DisplayName          string     `json:"display_name"`
}

func (q *Queries) MatchParticipants(ctx context.Context, matchID string) ([]MatchParticipantsRow, error) {
	rows, err := q.db.Query(ctx, matchParticipants, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchParticipantsRow{}
	for rows.Next() {
		var i MatchParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Seat,
			&i.ControllerGeneration,
			&i.DisconnectedAt,
			&i.LastSeenAt,
			&i.AbandonVote,
			&i.Handle,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchStateFor = `-- name: MatchStateFor :one
SELECT m.id,m.room_id,m.game_id,m.rules_version,m.status,m.end_reason,m.winner_id,m.ended_by,m.revision,m.version,
 extract(epoch FROM now()-m.awaiting_since)::float8 AS waited_seconds,
 me.controller_generation,s.schema_version,s.state,
 (SELECT coalesce(jsonb_agg(jsonb_build_object('user_id',p.user_id,'seat',p.seat,'handle',u.handle,'display_name',u.display_name,'disconnected_at',p.disconnected_at,'abandon_vote',p.abandon_vote) ORDER BY p.seat),'[]'::jsonb)
  FROM match_participants p JOIN users u ON u.id=p.user_id WHERE p.match_id=m.id)::jsonb AS participants,
 (SELECT coalesce(jsonb_agg(jsonb_build_object('revision',e.revision,'kind',e.kind,'payload',e.payload,'created_at',e.created_at) ORDER BY e.revision,e.event_index),'[]'::jsonb)
  FROM (SELECT ge.revision,ge.event_index,ge.kind,ge.payload,ge.created_at FROM game_events ge
        WHERE ge.match_id=m.id AND (ge.public OR ge.audience_user_id=$1::uuid)
        ORDER BY ge.revision DESC,ge.event_index DESC LIMIT 60) e)::jsonb AS events
FROM matches m
JOIN match_participants me ON me.match_id=m.id AND me.user_id=$1::uuid
JOIN LATERAL (SELECT gs.schema_version,gs.state FROM game_snapshots gs WHERE gs.match_id=m.id ORDER BY gs.revision DESC LIMIT 1) s ON true
WHERE m.id=$2::uuid
`

type MatchStateForParams struct {
	ViewerID string `json:"viewer_id"`
	MatchID  string `json:"match_id"`
}

type MatchStateForRow struct {
	ID                   string      `json:"id"`
	RoomID               string      `json:"room_id"`
	GameID               string      `json:"game_id"`
	RulesVersion         string      `json:"rules_version"`
	Status               string      `json:"status"`
	EndReason            pgtype.Text `json:"end_reason"`
	WinnerID             *string     `json:"winner_id"`
	EndedBy              *string     `json:"ended_by"`
	Revision             int64       `json:"revision"`
	Version              int64       `json:"version"`
	WaitedSeconds        float64     `json:"waited_seconds"`
	ControllerGeneration int64       `json:"controller_generation"`
	SchemaVersion        int32       `json:"schema_version"`
	State                []byte      `json:"state"`
	Participants         []byte      `json:"participants"`
	Events               []byte      `json:"events"`
}

// Everything one viewer's projection needs, read in one statement (one
// consistent snapshot, one round trip).
func (q *Queries) MatchStateFor(ctx context.Context, arg MatchStateForParams) (MatchStateForRow, error) {
	row := q.db.QueryRow(ctx, matchStateFor, arg.ViewerID, arg.MatchID)
	var i MatchStateForRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameID,
		&i.RulesVersion,
		&i.Status,
		&i.EndReason,
		&i.WinnerID,
		&i.EndedBy,
		&i.Revision,
		&i.Version,
		&i.WaitedSeconds,
		&i.ControllerGeneration,
		&i.SchemaVersion,
		&i.State,
		&i.Participants,
		&i.Events,
	)
	return i, err
}

const pruneEndedSnapshots = `-- name: PruneEndedSnapshots :exec
DELETE FROM game_snapshots s USING matches m
WHERE m.id=s.match_id AND m.status IN ('finished','abandoned') AND s.revision < m.revision
`

func (q *Queries) PruneEndedSnapshots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneEndedSnapshots)
	return err
}

const purgeOldMatches = `-- name: PurgeOldMatches :exec
DELETE FROM matches WHERE status IN ('finished','abandoned') AND finished_at < now()-interval '90 days'
`

func (q *Queries) PurgeOldMatches(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeOldMatches)
	return err
}

const recentEvents = `-- name: RecentEvents :many
SELECT revision,event_index,kind,payload,created_at FROM game_events
WHERE match_id=$1 AND (public OR audience_user_id=$2::uuid)
ORDER BY revision DESC,event_index DESC LIMIT 60
`

type RecentEventsParams struct {
	MatchID  string `json:"match_id"`
	ViewerID string `json:"viewer_id"`
}

type RecentEventsRow struct {
	Revision   int64     `json:"revision"`
	EventIndex int32     `json:"event_index"`
	Kind       string    `json:"kind"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) RecentEvents(ctx context.Context, arg RecentEventsParams) ([]RecentEventsRow, error) {
	rows, err := q.db.Query(ctx, recentEvents, arg.MatchID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentEventsRow{}
	for rows.Next() {
		var i RecentEventsRow
		if err := rows.Scan(
			&i.Revision,
			&i.EventIndex,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomGameState = `-- name: RoomGameState :one
SELECT m.id,m.game_id,m.rules_version,s.schema_version,s.state FROM matches m
JOIN LATERAL (SELECT gs.schema_version,gs.state FROM game_snapshots gs WHERE gs.match_id=m.id ORDER BY gs.revision DESC LIMIT 1) s ON true
WHERE m.room_id=$1 AND m.status IN ('playing','paused') ORDER BY m.created_at DESC LIMIT 1
`

type RoomGameStateRow struct {
	ID            string `json:"id"`
	GameID        string `json:"game_id"`
	RulesVersion  string `json:"rules_version"`
	SchemaVersion int32  `json:"schema_version"`
	State         []byte `json:"state"`
}

// The running match's engine and newest snapshot for a room, so platform
// policies that depend on game state (chat during trump selection) can ask
// the rules engine inside the caller's transaction.
func (q *Queries) RoomGameState(ctx context.Context, roomID string) (RoomGameStateRow, error) {
	row := q.db.QueryRow(ctx, roomGameState, roomID)
	var i RoomGameStateRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.RulesVersion,
		&i.SchemaVersion,
		&i.State,
	)
	return i, err
}

const setAbandonVote = `-- name: SetAbandonVote :exec
UPDATE match_participants SET abandon_vote=$3 WHERE match_id=$1 AND user_id=$2
`

type SetAbandonVoteParams struct {
	MatchID     string `json:"match_id"`
	UserID      string `json:"user_id"`
	AbandonVote bool   `json:"abandon_vote"`
}

func (q *Queries) SetAbandonVote(ctx context.Context, arg SetAbandonVoteParams) error {
	_, err := q.db.Exec(ctx, setAbandonVote, arg.MatchID, arg.UserID, arg.AbandonVote)
	return err
}

const setMatchStatus = `-- name: SetMatchStatus :exec
UPDATE matches SET status=$1,version=version+1,
 awaiting_since=CASE WHEN $1::text='playing' THEN now() ELSE awaiting_since END
WHERE id=$2
`

type SetMatchStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

// Resuming play restarts the turn clock.
func (q *Queries) SetMatchStatus(ctx context.Context, arg SetMatchStatusParams) error {
	_, err := q.db.Exec(ctx, setMatchStatus, arg.Status, arg.ID)
	return err
}

const setRoomStatus = `-- name: SetRoomStatus :exec
UPDATE rooms SET status=$2,revision=revision+1 WHERE id=$1
`

type SetRoomStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetRoomStatus(ctx context.Context, arg SetRoomStatusParams) error {
	_, err := q.db.Exec(ctx, setRoomStatus, arg.ID, arg.Status)
	return err
}

const staleControllers = `-- name: StaleControllers :many
UPDATE match_participants p SET disconnected_at=p.last_seen_at FROM matches m
WHERE m.id=p.match_id AND m.status IN ('playing','paused') AND p.disconnected_at IS NULL AND p.last_seen_at < now()-interval '45 seconds'
RETURNING p.match_id
`

func (q *Queries) StaleControllers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, staleControllers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var match_id string
		if err := rows.Scan(&match_id); err != nil {
			return nil, err
		}
		items = append(items, match_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeControl = `-- name: TakeControl :one
UPDATE match_participants SET controller_generation=controller_generation+1,last_seen_at=now(),disconnected_at=NULL
WHERE match_id=$1 AND user_id=$2 RETURNING controller_generation
`

type TakeControlParams struct {
	MatchID string `json:"match_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) TakeControl(ctx context.Context, arg TakeControlParams) (int64, error) {
	row := q.db.QueryRow(ctx, takeControl, arg.MatchID, arg.UserID)
	var controller_generation int64
	err := row.Scan(&controller_generation)
	return controller_generation, err
}
