// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountToken struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

type ChatReport struct {
	MessageID  int64     `json:"message_id"`
	ReporterID string    `json:"reporter_id"`
	Reason     string    `json:"reason"`
	CreatedAt  time.Time `json:"created_at"`
}

type Friendship struct {
	RequesterID string    `json:"requester_id"`
	RecipientID string    `json:"recipient_id"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type GameCommand struct {
	MatchID           string `json:"match_id"`
	ActorID           string `json:"actor_id"`
	CommandID         string `json:"command_id"`
	RequestHash       string `json:"request_hash"`
	ResultingRevision int64  `json:"resulting_revision"`
	Result            []byte `json:"result"`
}

type GameEvent struct {
	MatchID        string    `json:"match_id"`
	Revision       int64     `json:"revision"`
	EventIndex     int32     `json:"event_index"`
	Kind           string    `json:"kind"`
	AudienceUserID *string   `json:"audience_user_id"`
	Public         bool      `json:"public"`
	Payload        []byte    `json:"payload"`
	CreatedAt      time.Time `json:"created_at"`
}

type GameSnapshot struct {
	MatchID       string    `json:"match_id"`
	Revision      int64     `json:"revision"`
	SchemaVersion int32     `json:"schema_version"`
	State         []byte    `json:"state"`
	CreatedAt     time.Time `json:"created_at"`
}

type Invitation struct {
	ID         string      `json:"id"`
	RoomID     string      `json:"room_id"`
	InviterID  string      `json:"inviter_id"`
	TargetID   *string     `json:"target_id"`
	TokenHash  pgtype.Text `json:"token_hash"`
	ExpiresAt  time.Time   `json:"expires_at"`
	RevokedAt  *time.Time  `json:"revoked_at"`
	AcceptedAt *time.Time  `json:"accepted_at"`
}

type LoginDevice struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Match struct {
	ID           string     `json:"id"`
	RoomID       string     `json:"room_id"`
	GameID       string     `json:"game_id"`
	RulesVersion string     `json:"rules_version"`
	Status       string     `json:"status"`
	Revision     int64      `json:"revision"`
	WinnerID     *string    `json:"winner_id"`
	CreatedAt    time.Time  `json:"created_at"`
	FinishedAt   *time.Time `json:"finished_at"`
}

type MatchParticipant struct {
	MatchID              string     `json:"match_id"`
	UserID               string     `json:"user_id"`
	Seat                 int32      `json:"seat"`
	ControllerGeneration int64      `json:"controller_generation"`
	DisconnectedAt       *time.Time `json:"disconnected_at"`
}

type Outbox struct {
	ID          int64      `json:"id"`
	RoomID      string     `json:"room_id"`
	Kind        string     `json:"kind"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	DeliveredAt *time.Time `json:"delivered_at"`
}

type Room struct {
	ID           string    `json:"id"`
	HostID       string    `json:"host_id"`
	Name         string    `json:"name"`
	GameID       string    `json:"game_id"`
	RulesVersion string    `json:"rules_version"`
	Capacity     int32     `json:"capacity"`
	Status       string    `json:"status"`
	Revision     int64     `json:"revision"`
	CreatedAt    time.Time `json:"created_at"`
}

type RoomBan struct {
	RoomID    string    `json:"room_id"`
	UserID    string    `json:"user_id"`
	ActorID   string    `json:"actor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RoomChat struct {
	ID        int64     `json:"id"`
	RoomID    string    `json:"room_id"`
	UserID    string    `json:"user_id"`
	ClientID  string    `json:"client_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type RoomMember struct {
	RoomID     string    `json:"room_id"`
	UserID     string    `json:"user_id"`
	Seat       int32     `json:"seat"`
	Ready      bool      `json:"ready"`
	JoinedAt   time.Time `json:"joined_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type Session struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
}

type User struct {
	ID            string     `json:"id"`
	Email         string     `json:"email"`
	Handle        string     `json:"handle"`
	DisplayName   string     `json:"display_name"`
	PasswordHash  string     `json:"password_hash"`
	EmailVerified bool       `json:"email_verified"`
	CreatedAt     time.Time  `json:"created_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type UserBlock struct {
	UserID    string    `json:"user_id"`
	BlockedID string    `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
}
