// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at=now() WHERE id=$1 AND target_id IS NOT NULL
`

func (q *Queries) AcceptInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const addMember = `-- name: AddMember :exec
INSERT INTO room_members(room_id,user_id,seat) VALUES($1,$2,$3)
`

type AddMemberParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
	Seat   int32  `json:"seat"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.RoomID, arg.UserID, arg.Seat)
	return err
}

const bumpRoom = `-- name: BumpRoom :exec
UPDATE rooms SET revision=revision+1 WHERE id=$1
`

func (q *Queries) BumpRoom(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpRoom, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations(room_id,inviter_id,target_id,token_hash) VALUES($1,$2,NULLIF($3::text,'')::uuid,NULLIF($4::text,'')) RETURNING id,expires_at
`

type CreateInvitationParams struct {
	RoomID    string `json:"room_id"`
	InviterID string `json:"inviter_id"`
	TargetID  string `json:"target_id"`
	TokenHash string `json:"token_hash"`
}

type CreateInvitationRow struct {
	ID        string    `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.RoomID,
		arg.InviterID,
		arg.TargetID,
		arg.TokenHash,
	)
	var i CreateInvitationRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms(host_id,name,capacity) VALUES($1,$2,$3) RETURNING id, host_id, name, game_id, rules_version, capacity, status, revision, created_at
`

type CreateRoomParams struct {
	HostID   string `json:"host_id"`
	Name     string `json:"name"`
	Capacity int32  `json:"capacity"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.HostID, arg.Name, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.GameID,
		&i.RulesVersion,
		&i.Capacity,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const invitation = `-- name: Invitation :one
SELECT id, room_id, inviter_id, target_id, token_hash, expires_at, revoked_at, accepted_at FROM invitations WHERE id=$1
`

func (q *Queries) Invitation(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRow(ctx, invitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.InviterID,
		&i.TargetID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const invitationByToken = `-- name: InvitationByToken :one
SELECT id, room_id, inviter_id, target_id, token_hash, expires_at, revoked_at, accepted_at FROM invitations WHERE token_hash=$1
`

func (q *Queries) InvitationByToken(ctx context.Context, tokenHash pgtype.Text) (Invitation, error) {
	row := q.db.QueryRow(ctx, invitationByToken, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.InviterID,
		&i.TargetID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS(SELECT 1 FROM room_members WHERE room_id=$1 AND user_id=$2)
`

type IsMemberParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockRoom = `-- name: LockRoom :one
SELECT id, host_id, name, game_id, rules_version, capacity, status, revision, created_at FROM rooms WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockRoom(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, lockRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.GameID,
		&i.RulesVersion,
		&i.Capacity,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const members = `-- name: Members :many
SELECT u.id,u.handle,u.display_name,m.seat,m.ready,m.joined_at FROM room_members m JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 ORDER BY m.seat
`

type MembersRow struct {
	ID          string    `json:"id"`
	Handle      string    `json:"handle"`
	DisplayName string    `json:"display_name"`
	Seat        int32     `json:"seat"`
	Ready       bool      `json:"ready"`
	JoinedAt    time.Time `json:"joined_at"`
}

func (q *Queries) Members(ctx context.Context, roomID string) ([]MembersRow, error) {
	rows, err := q.db.Query(ctx, members, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembersRow{}
	for rows.Next() {
		var i MembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Seat,
			&i.Ready,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myInvitations = `-- name: MyInvitations :many
SELECT i.id,i.room_id,i.inviter_id,i.expires_at,r.name FROM invitations i JOIN rooms r ON r.id=i.room_id
WHERE i.target_id=$1::uuid AND i.expires_at>now() AND i.revoked_at IS NULL AND i.accepted_at IS NULL AND r.status='waiting' ORDER BY i.expires_at LIMIT 100
`

type MyInvitationsRow struct {
	ID        string    `json:"id"`
	RoomID    string    `json:"room_id"`
	InviterID string    `json:"inviter_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Name      string    `json:"name"`
}

func (q *Queries) MyInvitations(ctx context.Context, userID string) ([]MyInvitationsRow, error) {
	rows, err := q.db.Query(ctx, myInvitations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyInvitationsRow{}
	for rows.Next() {
		var i MyInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.InviterID,
			&i.ExpiresAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myRooms = `-- name: MyRooms :many
SELECT r.id, r.host_id, r.name, r.game_id, r.rules_version, r.capacity, r.status, r.revision, r.created_at FROM rooms r JOIN room_members m ON m.room_id=r.id WHERE m.user_id=$1 AND r.status<>'closed' ORDER BY r.created_at DESC LIMIT 100
`

func (q *Queries) MyRooms(ctx context.Context, userID string) ([]Room, error) {
	rows, err := q.db.Query(ctx, myRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Name,
			&i.GameID,
			&i.RulesVersion,
			&i.Capacity,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetReady = `-- name: ResetReady :exec
UPDATE room_members SET ready=false WHERE room_id=$1
`

func (q *Queries) ResetReady(ctx context.Context, roomID string) error {
	_, err := q.db.Exec(ctx, resetReady, roomID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE invitations SET revoked_at=now() WHERE id=$1 AND inviter_id=$2
`

type RevokeInvitationParams struct {
	ID        string `json:"id"`
	InviterID string `json:"inviter_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.InviterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const room = `-- name: Room :one
SELECT id, host_id, name, game_id, rules_version, capacity, status, revision, created_at FROM rooms WHERE id=$1
`

func (q *Queries) Room(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRow(ctx, room, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Name,
		&i.GameID,
		&i.RulesVersion,
		&i.Capacity,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const setReady = `-- name: SetReady :exec
UPDATE room_members SET ready=$3 WHERE room_id=$1 AND user_id=$2
`

type SetReadyParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
	Ready  bool   `json:"ready"`
}

func (q *Queries) SetReady(ctx context.Context, arg SetReadyParams) error {
	_, err := q.db.Exec(ctx, setReady, arg.RoomID, arg.UserID, arg.Ready)
	return err
}
