// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package store

import (
	"context"
)

const acceptFriend = `-- name: AcceptFriend :execrows
UPDATE friendships SET status='accepted' WHERE requester_id=$1 AND recipient_id=$2 AND status='pending'
`

type AcceptFriendParams struct {
	RequesterID string `json:"requester_id"`
	RecipientID string `json:"recipient_id"`
}

func (q *Queries) AcceptFriend(ctx context.Context, arg AcceptFriendParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptFriend, arg.RequesterID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS(SELECT 1 FROM friendships WHERE status='accepted' AND ((requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1)))
`

type AreFriendsParams struct {
	RequesterID string `json:"requester_id"`
	RecipientID string `json:"recipient_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.RequesterID, arg.RecipientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks(user_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	UserID    string `json:"user_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.UserID, arg.BlockedID)
	return err
}

const hasBlock = `-- name: HasBlock :one
SELECT EXISTS(SELECT 1 FROM user_blocks WHERE (user_id=$1 AND blocked_id=$2) OR (user_id=$2 AND blocked_id=$1))
`

type HasBlockParams struct {
	UserID    string `json:"user_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) HasBlock(ctx context.Context, arg HasBlockParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlock, arg.UserID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFriendships = `-- name: ListFriendships :many
SELECT f.requester_id,f.recipient_id,f.status,u.id,u.handle,u.display_name
FROM friendships f JOIN users u ON u.id=CASE WHEN f.requester_id=$1 THEN f.recipient_id ELSE f.requester_id END
WHERE f.requester_id=$1 OR f.recipient_id=$1 ORDER BY f.created_at DESC LIMIT 100
`

type ListFriendshipsRow struct {
	RequesterID string `json:"requester_id"`
	RecipientID string `json:"recipient_id"`
	Status      string `json:"status"`
	ID          string `json:"id"`
	Handle      string `json:"handle"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListFriendships(ctx context.Context, requesterID string) ([]ListFriendshipsRow, error) {
	rows, err := q.db.Query(ctx, listFriendships, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendshipsRow{}
	for rows.Next() {
		var i ListFriendshipsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.RecipientID,
			&i.Status,
			&i.ID,
			&i.Handle,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSocialPair = `-- name: LockSocialPair :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text,0))
`

func (q *Queries) LockSocialPair(ctx context.Context, pair string) error {
	_, err := q.db.Exec(ctx, lockSocialPair, pair)
	return err
}

const removeFriend = `-- name: RemoveFriend :exec
DELETE FROM friendships WHERE (requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1)
`

type RemoveFriendParams struct {
	RequesterID string `json:"requester_id"`
	RecipientID string `json:"recipient_id"`
}

func (q *Queries) RemoveFriend(ctx context.Context, arg RemoveFriendParams) error {
	_, err := q.db.Exec(ctx, removeFriend, arg.RequesterID, arg.RecipientID)
	return err
}

const requestFriend = `-- name: RequestFriend :exec
INSERT INTO friendships(requester_id,recipient_id) VALUES($1,$2) ON CONFLICT DO NOTHING
`

type RequestFriendParams struct {
	RequesterID string `json:"requester_id"`
	RecipientID string `json:"recipient_id"`
}

func (q *Queries) RequestFriend(ctx context.Context, arg RequestFriendParams) error {
	_, err := q.db.Exec(ctx, requestFriend, arg.RequesterID, arg.RecipientID)
	return err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks WHERE user_id=$1 AND blocked_id=$2
`

type UnblockUserParams struct {
	UserID    string `json:"user_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.UserID, arg.BlockedID)
	return err
}
